### ISSUE TITLE
Add support for cname buckets

### ISSUE THREAD

**Issue by Alofoxx** [dcoles/acme-linode-objectstorage#1]
If you add a flag for the bucket name and separate it from the domain it would allow for creating certs for the custom domains set for the bucket.

**Comment by dcoles** [comment]
Unfortunately Linode requires that the bucket name matches the name on the certificate. From the [Linode documentation](https://www.linode.com/docs/guides/enable-ssl-for-object-storage/#create-an-object-storage-bucket):

>All Object Storage Buckets using an SSL certificate created by a user **must match a Fully Qualified Domain Name under the user’s control**. For example, if you will be using an SSL certificate for test.example.com, the bucket name should also be test.example.com.

Attempting to upload a certificate that does not match the bucket name results in an error:
![image](https://user-images.githubusercontent.com/1007415/105121134-6e72c700-5a88-11eb-943e-603288006fb7.png)

This might be something that could be fixed by Linode, in which case a separate bucket flag would make sense.
